"""Crear tablas asistencia y permisos

Revision ID: 2aa1c5d95885
Revises: ae933ef8d298
Create Date: 2025-11-17 17:03:10.183859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa1c5d95885'
down_revision = 'ae933ef8d298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('horas_extra', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_table('permisos',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('autorizado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permisos')
    op.drop_table('asistencias')
    # ### end Alembic commands ###
