"""Actualizar estructura de tablas según modelo ER

Revision ID: 3e8f481c2c4e
Revises: b30e4b224463
Create Date: 2025-10-27 09:51:12.928283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8f481c2c4e'
down_revision = 'b30e4b224463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sueldo_base', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('creado_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('modificado_por', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('cargos_nombre_key'), type_='unique')
        batch_op.drop_column('nivel')
        batch_op.drop_column('departamento')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_ingreso', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_egreso', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tipo_cuenta_bancaria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_cuenta_bancaria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('modalidad_fondo_reserva', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('modalidad_decimos', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('creado_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('modificado_por', sa.Integer(), nullable=True))
        batch_op.alter_column('id_cargo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nombres',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cedula',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('empleados_email_key'), type_='unique')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'])
        batch_op.drop_column('salario')
        batch_op.drop_column('fecha_contratacion')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('email')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_id_empleado_fkey'), type_='foreignkey')
        batch_op.drop_column('id_empleado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empleado', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('usuarios_id_empleado_fkey'), 'empleados', ['id_empleado'], ['id'])

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_contratacion', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('salario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('empleados_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('cedula',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nombres',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('id_cargo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('modificado_por')
        batch_op.drop_column('creado_por')
        batch_op.drop_column('modalidad_decimos')
        batch_op.drop_column('modalidad_fondo_reserva')
        batch_op.drop_column('numero_cuenta_bancaria')
        batch_op.drop_column('tipo_cuenta_bancaria')
        batch_op.drop_column('fecha_egreso')
        batch_op.drop_column('fecha_ingreso')
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departamento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nivel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('cargos_nombre_key'), ['nombre'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('modificado_por')
        batch_op.drop_column('creado_por')
        batch_op.drop_column('sueldo_base')

    # ### end Alembic commands ###
