"""Initial migration

Revision ID: b5911eac7f0a
Revises: 
Create Date: 2026-01-08 02:13:32.190491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5911eac7f0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('nombre_cargo', sa.String(length=100), nullable=False),
    sa.Column('sueldo_base', sa.Float(), nullable=False),
    sa.Column('permisos', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_cargo')
    )
    op.create_table('log_transaccional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=False),
    sa.Column('operacion', sa.String(length=20), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('cedula', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('tipo_cuenta_bancaria', sa.String(length=50), nullable=True),
    sa.Column('numero_cuenta_bancaria', sa.String(length=50), nullable=True),
    sa.Column('modalidad_fondo_reserva', sa.String(length=20), nullable=True),
    sa.Column('modalidad_decimos', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos.id_cargo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('horas_extra', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_table('hoja_vida',
    sa.Column('id_hoja_vida', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('nombre_documento', sa.String(length=255), nullable=True),
    sa.Column('institucion', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_finalizacion', sa.Date(), nullable=True),
    sa.Column('ruta_archivo_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id_hoja_vida')
    )
    op.create_table('horario',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('dia_laborables', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('hora_entrada', sa.Time(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('descanso_minutos', sa.Integer(), nullable=True),
    sa.Column('turno', sa.String(length=100), nullable=True),
    sa.Column('inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('fin_vigencia', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('nominas',
    sa.Column('id_nomina', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=20), nullable=True),
    sa.Column('sueldo_base', sa.Float(), nullable=False),
    sa.Column('horas_extra', sa.Float(), nullable=False),
    sa.Column('total_desembolsar', sa.Float(), nullable=False),
    sa.Column('fecha_generacion', sa.Date(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id_nomina')
    )
    op.create_table('permisos',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('autorizado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    op.create_table('rubros',
    sa.Column('id_rubro', sa.Integer(), nullable=False),
    sa.Column('id_nomina', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('autorizado_por', sa.String(length=200), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('operacion', sa.String(length=10), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_nomina'], ['nominas.id_nomina'], ),
    sa.PrimaryKeyConstraint('id_rubro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rubros')
    op.drop_table('permisos')
    op.drop_table('nominas')
    op.drop_table('horario')
    op.drop_table('hoja_vida')
    op.drop_table('asistencias')
    op.drop_table('empleados')
    op.drop_table('usuarios')
    op.drop_table('log_transaccional')
    op.drop_table('cargos')
    # ### end Alembic commands ###
